import { SiteHeader } from '@/components/SiteHeader'
import '@/styles/globals.css'
import { Readex_Pro } from 'next/font/google'

const readexPro = Readex_Pro({ subsets: ['arabic'], weight: '400' })

export const metadata = {
  title: 'الرئيسية - لوحة التحكم',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode }) {
  return (
    <html lang="ar" dir='rtl'>
      <body className={readexPro.className}>
        <SiteHeader />
        {children}
        </body>
    </html>
  )
}
